#!/usr/bin/env bash
# One-time setup for the Crema order-notification Worker.
# Run in Git Bash from the order-worker folder AFTER: npx wrangler login
set -e
cd "$(dirname "$0")"

echo "== 1/5  Generating VAPID keys =="
KEYS_JSON="$(npx --yes web-push generate-vapid-keys --json)"
PUB="$(node -e "process.stdout.write(JSON.parse(process.argv[1]).publicKey)" "$KEYS_JSON")"
PRIV="$(node -e "process.stdout.write(JSON.parse(process.argv[1]).privateKey)" "$KEYS_JSON")"
echo "   public key: $PUB"

echo "== 2/5  Creating KV namespace =="
KV_OUT="$(npx --yes wrangler kv namespace create CREMA 2>&1 || true)"
echo "$KV_OUT"
KV_ID="$(printf '%s' "$KV_OUT" | grep -oE 'id = "[a-f0-9]+"' | head -1 | grep -oE '[a-f0-9]{20,}')"
if [ -z "$KV_ID" ]; then
  echo "!! Could not read the KV id automatically. Copy it from the output above and paste it into wrangler.toml (replace PUT_KV_ID_HERE), then re-run from step 3 by hand."
  exit 1
fi
echo "   KV id: $KV_ID"

echo "== 3/5  Writing wrangler.toml =="
# portable in-place edits
sed -i.bak "s/PUT_KV_ID_HERE/$KV_ID/" wrangler.toml
sed -i.bak "s#PUT_VAPID_PUBLIC_HERE#$PUB#" wrangler.toml
rm -f wrangler.toml.bak

echo "== 4/5  Storing the private key as a Worker secret =="
printf '%s' "$PRIV" | npx --yes wrangler secret put VAPID_PRIVATE

echo "== 5/5  Deploying =="
DEPLOY_OUT="$(npx --yes wrangler deploy 2>&1)"
echo "$DEPLOY_OUT"
URL="$(printf '%s' "$DEPLOY_OUT" | grep -oE 'https://[a-z0-9._-]+\.workers\.dev' | head -1)"
if [ -z "$URL" ]; then
  echo "!! Deployed, but could not read the URL. Find it in the output above (…workers.dev) and paste it into ../push-config.js as api."
  exit 1
fi
echo "   Worker URL: $URL"

echo "== Writing ../push-config.js =="
cat > ../push-config.js <<EOF
/* Push config — generated by order-worker/setup.sh. */
self.CREMA_PUSH = {
  api: "$URL",
  vapidPublic: "$PUB"
};
EOF

echo ""
echo "DONE. Now publish the site so phones pick up the config:"
echo "   cd .. && git add -A && git commit -m \"wire push config\" && git push"
echo "Then open Crema on your phone, go to the Order tab, and tap \"Get order alerts on this phone\"."
